import type { NextPage } from 'next'
import Head from 'next/head'
import Input from '@components/Input/Input'
import ContextTest from '@components/ContextTest/ContextTest'
import { Currency } from '@components/currency/currency'
import { useEffect, useState } from 'react'
import { useAppContext } from '@hooks/context'


const Home: NextPage = () => {
	const context = useAppContext()

	const [fromCurrency, setFromCurrency] = useState("USD")
	const [toCurrency, setToCurrency] = useState("THB")

	const [amount, setAmount] = useState(1)
	const [exchangeRates, setExchangeRates] = useState(0)
	const [checkFrome, setCheckFrome] = useState(true)

	let fromAmount, toAmount

	if (checkFrome) {
		fromAmount = amount;
		toAmount = (amount * exchangeRates).toFixed(2)
	} else {
		toAmount = amount;
		fromAmount = (amount / exchangeRates).toFixed(2)
	}

	let choice: any;
	useEffect(() => {
		const url = `https://api.exchangerate-api.com/v4/latest/${fromCurrency}`
		fetch(url)
			.then(res => {
				return res.json()
			})
			.then(data => {
				context.setCurrencyChoice(Object.keys(data.rates))
				setExchangeRates(data.rates[toCurrency]);
			})
		// .then(data => context.setCurrencyChoice(Object.keys(data.rates)))
	}, [fromCurrency, toCurrency])

	const amountFromCurrency = (e) => {
		setAmount(e.target.value)
		setCheckFrome(true)
	}

	const amountToCurrency = (e) => {
		setAmount(e.target.value)
		setCheckFrome(false);
	}
	return (
		<>
			<Head>
				<title>Current Exchange App</title>
				<meta
					name="Current Exchange App"
					content="Generated by Akiira 2022"
				/>
				<meta name="google-adsense-account" content="ca-pub-3436829376802292"></meta>
				<link rel="icon" href="exchange.png" />
			</Head>

			<div>
				{/* <img src="/money.png" className="money" /> */}
				<h1 className="">Current Exchange App</h1>
				<div className="container">
					<Currency
						selectCurrency={fromCurrency}
						changeCurrency={(e) => setFromCurrency(e.target.value)}
						amount={fromAmount}
						onChangeAmount={amountFromCurrency}
					/>
					<div className="equal"> = </div>
					<Currency
						selectCurrency={toCurrency}
						changeCurrency={(e) => setToCurrency(e.target.value)}
						amount={toAmount}
						onChangeAmount={amountToCurrency}
					/>
				</div>
			</div>
		</>
	)
}

export default Home